# Generated by Django 2.0.2 on 2020-02-02 23:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200202_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 2, 23, 31, 3, 546881, tzinfo=utc)),
        ),
    ]
