# Generated by Django 2.0.2 on 2020-02-02 23:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200202_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 2, 23, 32, 3, 49381, tzinfo=utc)),
        ),
    ]
